const productos = [
    {
      id: 1,
      imagen: "https://i.postimg.cc/52JFWVcN/Buy-directly-from-the-world-s-most-awesome-indie-brands-Or-open-a-free-online-store.jpg",
      titulo: "Buzo Trasher",
      talles: "x, xl, xxl",
      colores: "Blanco, negro, rojo, azul y naranja.",
      precio: 3900,
    },
    {
      id: 2,
      imagen: "https://i.postimg.cc/Dw5mV4dB/Autumn-and-Winter-Candy-Colored-Sweatshirt-Smiley-Face-Crying-Face-Printing-Pattern-Hooded-Winter-T.jpg",
      titulo: "Buzo doble cara",
      talles: "x, xl, xxl",
      colores: "Verde, rojo, violeta, blanco y negro.",
      precio: 2900,
    },
    {
      id: 3,
      imagen: "https://i.postimg.cc/PJG5bWTr/descarga-4.jpg",
      titulo: "Buzo dream",
      talles: "x, xl, xxl",
      colores: "Blanco, negro, rojo y amarillo.",
      precio: 2999,
    },
    {
    
      id: 4,
      imagen: "https://i.postimg.cc/yNbdxqGR/descarga-5.jpg",
      titulo: "Buzo eyes",
      talles: "x, xl, xxl",
      colores: "Blanco, gris, negro, rojo, azul y naranja.",
      precio: 4900,
    },
    {
      id: 5,
      imagen: "https://i.postimg.cc/MTfGjPkF/Fashion-Alien-Monster-Pattern-Casual-Loose-Long-Sleeve-Hoodie.jpg",
      titulo: "Buzo alien",
      talles: "x, xl, xxl",
      colores: "Batik rosa, batik rojo, batik azul y batik amarillo.",
      precio: 5900,
    },
    {
      id: 6,
      imagen: "https://i.postimg.cc/HW5xYh9J/Marc-Jacobs-and-Cactus-Plant-Flea-Market-Unveil-Unexpected-Collab.jpg",
      titulo: "Buzo shameless",
      talles: "x, xl, xxl",
      colores: "Blanco, negro, naranja y celeste.",
      precio: 3900,
    },
    {
      id: 7,
      imagen: "https://i.postimg.cc/j2rRnR4D/Mens-Funny-Smile-Face-Chest-Print-Solid-Casual-Loose-Pullover-Sweatshirts.png",
      titulo: "Buzo funny-smile",
      talles: "x, xl, xxl",
      colores: "Blanco, negro, rojo, amarillo y celeste.",
      precio: 3999,
    },
    {
      id: 8,
      imagen: "https://i.postimg.cc/ncJLCG33/Mens-Rose-Japanese-Character-Print-Cotton-Casual-Drawstring-Overhead-Hoodies.jpg",
      titulo: "Buzo rose-japanese",
      talles: "x, xl, xxl",
      colores: "Blanco, negro, azul,rosa y naranja.",
      precio: 3900,
    },
    {
      id: 9,
      imagen: "https://i.postimg.cc/TPpdZ7P3/Novelty-Womens-Hoodie-Cat-Knife-Letter-What-Printed-Knitted-Trim-Drawstring-Long-Sleeve-Relaxed-Fitt.png",
      titulo: "Buzo cat",
      talles: "x, xl, xxl",
      colores: "Blanco, negro, verde, celeste y violeta.",
      precio: 3900,
    },
    {
      id: 10,
      imagen: "https://i.postimg.cc/rFNwWRbM/Sudaderas-de-tallas-grandes-Las-mejores-ofertas-SHEIN-Espa-a.png",
      titulo: "Buzo moon",
      talles: "x, xl, xxl",
      colores: "Blanco, negro, rosa, naranja, gris y azul.",
      precio: 3999,
    },

    {
      id: 11,
      imagen: "https://i.postimg.cc/R0gW1ckK/buzobasic.jpg",
      titulo: "Buzo basic",
      talles: "x, xl, xxl",
      colores: "Blanco, negro, rosa, naranja, gris, verde, celeste, rojo y amarillo.",
      precio: 2999,
    },
    {
      id: 12,
      imagen: "https://i.postimg.cc/xCqc6XQ7/buzodragon.jpg",
      titulo: "Buzo dragon",
      talles: "x, xl, xxl",
      colores: "Negro y blanco, celeste y violeta, verde y azul.",
      precio: 4999,
    },
    
  ];

  export default productos;