const productos = [
    
    {
      id: 1,
      imagen: "https://i.postimg.cc/MTfGjPkF/Fashion-Alien-Monster-Pattern-Casual-Loose-Long-Sleeve-Hoodie.jpg",
      titulo: "BUZO ALIEN",
      detalle: "Buzo unisex con corte holgado, cuello con capucha y cordon para un ajuste regulable, bolsillo tipo canguro. Hecho con tela de algodón  frisado. Talles: x,xl,xxl.",
      talles: "x, xl, xxl",
      colores: "Batik rosa, batik rojo, batik azul, batik amarillo.",
      stock: 10,
      category: "buzos",
      precio: 5900,
      
    },
  
    {
      id: 2,
      imagen: "https://i.postimg.cc/ncJLCG33/Mens-Rose-Japanese-Character-Print-Cotton-Casual-Drawstring-Overhead-Hoodies.jpg",
      titulo: "BUZO ROSE-JAPANESE",
      detalle: "Buzo unisex con corte holgado, cuello con capucha y cordon para un ajuste regulable. Hecho con tela de algodón frisado.",
      talles: "x, xl, xxl",
      colores: "Blanco, negro, azul,rosa, naranja.",
      stock: 15,
      category: "buzos",
      precio: 3900,
    },
    
   
    {
      id: 3,
      imagen: "https://i.postimg.cc/R0gW1ckK/buzobasic.jpg",
      titulo: "BUZO BASIC",
      detalle: "Buzo unisex con corte holgado, cuello con capucha y cordon para un ajuste regulable, bolsillo tipo canguro. Hecho con tela de algodón frisado o rustico.",
      talles: "x, xl, xxl",
      colores: "Blanco, negro, rosa, naranja, gris, verde, celeste, rojo, amarillo.",
      stock: 30,
      category: "buzos",
      precio: 2999,
    },
    {
      id: 4,
      imagen: "https://i.postimg.cc/xCqc6XQ7/buzodragon.jpg",
      titulo: "BUZO DRAGON",
      detalle: "Buzo unisex con corte holgado, cuello con capucha y cordon para un ajuste regulable, bolsillo tipo canguro. Hecho con tela de algodón frisado.",
      talles: "x, xl, xxl",
      colores: "Negro y blanco, celeste y violeta, verde y azul.",
      stock: 15,
      category: "buzos",
      precio: 4999,
    }, {
      id: 5,
      imagen: "https://i.postimg.cc/15XPCnX2/Aveuri-2022-Vintage-Square-Sunglasses-Women-Men-Shades-Classic-Sun-Glasses-Female-Male-Brand-Design.jpg",
      titulo: "ANTEOJOS CLASSIC",
      detalle: "Anteojos de sol con formato cuadrado, lente de policarbonato, armazon de metal.",
      colores: "Negro, amarillo, azul, verde, rojo.",
      stock: 12,
      category: "accesorios",
      precio: 2200
    }, {
      id: 6,
      imagen: "https://i.postimg.cc/gcNmHqz3/descarga-19.jpg",
      titulo: "ANTEOJOS VINTAGE",
      detalle: "Anteojos de sol con formato redondo, lente de policarbonato, armazon de metal.",
      colores: "Negro, rojo, violeta, celeste.",
      stock: 8,
      category: "accesorios",
      precio: 2200,
    },
    {
      id: 7,
      imagen: "https://i.postimg.cc/Fs6v2rJR/Blank-Cotton-Bucket-Hat-Walmart-com.jpg",
      titulo: "PILUSO LISO",
      detalle: "Piluso liso de algodon, no ajustable.",
      talles: "x, xl, xxl",
      colores: "Negro, blanco, rojo, violeta, gris, amarillo, verde.",
      stock: 18,
      category: "accesorios",
      precio: 2400,
    },
    {
      id: 8,
      imagen: "https://i.postimg.cc/HnZmWHZ6/descarga-18.jpg",
      titulo: "GORRA MOTOR RACING TEAM",
      detalle: "Gorra vintage de algodon con vicera.",
      colores: "Azul y bordó, verde militar y beige, celeste y negra.",
      talles: "Unico, con hebilla de metal ajustable.",
      stock: 10,
      category: "accesorios",
      precio: 2700,
    },
    {
      id: 9,
      imagen: "https://i.postimg.cc/cJhxD6Pb/social.jpg",
      titulo: "JOGGINS SOCIAL",
      detalle: "Joggins unisex con corte holgado de algodon frisado",
      talles: "x, xl, xxl",
      colores: "Negro, blanco, celeste, verde manzana, rojo.",
      stock: 7,
      category: "joggins",
      precio: 4999,
    },
    {
      id: 10,
      imagen: "https://i.postimg.cc/B6S4Ws2w/batik.jpg",
      titulo: "JOGGINS BATIK",
      detalle: "Joggins unisex con corte holgado de algodon frisado.",
      talles: "x, xl, xxl",
      colores: "Negro, celeste, violeta, amarillo, verde.",
      stock: 20,
      category: "joggins",
      precio: 5500,
    },
    {
      id: 11,
      imagen: "https://i.postimg.cc/6q63hnHq/nirvana.jpg",
      titulo: "JOGGINS NIRVANA",
      detalle: "Joggins unisex con corte holgado de algodon frisado." ,
      talles: "x, xl, xxl",
      colores: "Negro, balanco, gris.",
      stock: 13,
      category: "joggins",
      precio: 4999,
    },
    {
      id: 12,
      imagen: "https://i.postimg.cc/bJhdsKkQ/likeyou.jpg",
      titulo: "JOGGINS LIKE YOU",
      detalle: "Joggins unisex con corte holgado de algodon frisado.",
      talles: "x, xl, xxl",
      colores: "Negro, blanco, verde, naranja,  azul.",
      stock: 17,
      category: "joggins",
      precio: 4400,
    },


    
  ];

  export default productos;